// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5OaWoglpI7QkKqSD6bpZgqBYzKTIXaJg',
    appId: '1:484105114194:web:95fd96d9e0f5a02778058b',
    messagingSenderId: '484105114194',
    projectId: 'portfolio-57737',
    authDomain: 'portfolio-57737.firebaseapp.com',
    storageBucket: 'portfolio-57737.firebasestorage.app',
    measurementId: 'G-3NPYG7N9BZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP0KlhmTzlbKGHNO7rlEU79a--qwOPaa0',
    appId: '1:484105114194:android:9fb4c2c2de84d6d278058b',
    messagingSenderId: '484105114194',
    projectId: 'portfolio-57737',
    storageBucket: 'portfolio-57737.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9Sqye2ysDzmg3pQ1dJdOcsXhS2KINcXY',
    appId: '1:484105114194:ios:599f67150d16b54878058b',
    messagingSenderId: '484105114194',
    projectId: 'portfolio-57737',
    storageBucket: 'portfolio-57737.firebasestorage.app',
    iosBundleId: 'com.example.moneycontrol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9Sqye2ysDzmg3pQ1dJdOcsXhS2KINcXY',
    appId: '1:484105114194:ios:599f67150d16b54878058b',
    messagingSenderId: '484105114194',
    projectId: 'portfolio-57737',
    storageBucket: 'portfolio-57737.firebasestorage.app',
    iosBundleId: 'com.example.moneycontrol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5OaWoglpI7QkKqSD6bpZgqBYzKTIXaJg',
    appId: '1:484105114194:web:d73e2c066249003d78058b',
    messagingSenderId: '484105114194',
    projectId: 'portfolio-57737',
    authDomain: 'portfolio-57737.firebaseapp.com',
    storageBucket: 'portfolio-57737.firebasestorage.app',
    measurementId: 'G-K1H0CBB2Y7',
  );
}
